### ISSUE TITLE
Not working with anchors and references :-(

### ISSUE THREAD

**Issue by mmrwoods** [wimglenn/oyaml#2]
Hi,

I've just tried to use `oyaml` in a project as it's just what I need, but I've run into a problem loading my yaml config file which makes use of anchors and references.

I get error `yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'` the first time a reference is encountered.

A complete example with a simple test file...

```
$ cat foo.yml
defaults:
  all: &all
    product: foo
  development: &development
    <<: *all
    profile: bar

development:
  platform:
    <<: *development
    host: baz

$ python3
Python 3.5.2 (default, Oct 18 2016, 11:56:15)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import oyaml as yaml
>>> yaml.load(open('foo.yml', 'r'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/site-packages/oyaml-0.1-py3.5.egg/oyaml.py", line 15, in _constructor
    return OrderedDict(loader.construct_pairs(node))
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/site-packages/oyaml-0.1-py3.5.egg/oyaml.py", line 15, in _constructor
    return OrderedDict(loader.construct_pairs(node))
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/site-packages/oyaml-0.1-py3.5.egg/oyaml.py", line 15, in _constructor
    return OrderedDict(loader.construct_pairs(node))
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 140, in construct_pairs
    key = self.construct_object(key_node, deep=deep)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "foo.yml", line 5, column 5
>>>
```

BTW, I'm using yaml version 3.12

**Comment by wimglenn** [comment]
Hi @mmrwoods thanks for the report.  I was able to [reproduce](https://travis-ci.org/wimglenn/oyaml/jobs/346110429) your issue, will investigate.

**Comment by wimglenn** [comment]
@mmrwoods   I've just put a v0.2 to PyPI, could you try it out and let me know if it addresses the issue?  Thanks.

**Comment by mmrwoods** [comment]
Thanks @wimglenn, I've just tested my project with version 0.2 and it works perfectly :-)
