### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by aylusltd** [wimglenn/oyaml#28]
tried pip installing and getting this:

```
Traceback (most recent call last):
  File "/mnt/c/Users/<XXXXX>/johnnydep/johnnydep/__main__.py", line 1, in <module>
    from cli import main
  File "/mnt/c/Users/<XXXXX>/johnnydep/johnnydep/cli.py", line 10, in <module>
    from compat import dict
  File "/mnt/c/Users/<XXXXX>/johnnydep/johnnydep/compat.py", line 3, in <module>
    import oyaml
  File "/home/<XXXXX>/.local/lib/python3.10/site-packages/oyaml.py", line 5, in <module>
    import yaml as pyyaml
ModuleNotFoundError: No module named 'yaml' 
```

which seems right since yaml isn't a module.

**Comment by wimglenn** [comment]
yaml is the import name of PyYAML.  It’s a dependency of oyaml, and should have been installed automatically by pip. I’m not sure what went wrong on your system, but you can just installed PyYAML to get going.
