### ISSUE TITLE
can't safely dump OrderedDict

### ISSUE THREAD

**Issue by cjw296** [wimglenn/oyaml#4]
```python
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from oyaml import safe_dump
>>> from collections import OrderedDict
>>> safe_dump(OrderedDict([('x', 1), ('y', 2)])
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "lib/python3.6/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File lib/python3.6/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "lib/python3.6/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "lib/python3.6/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: OrderedDict([('x', 1), ('y', 2)])
```

**Comment by wimglenn** [comment]
This is the same behaviour as PyYAML safe_dump, though.  What representation would you like to see?

**Comment by cjw296** [comment]
Same as for dict.

**Comment by wimglenn** [comment]
OK.  Will get it in a v0.3 release when I have the time (PRs welcome!).
